Repository POPCONG/POPCONG_BE, pull requests merged in 2025-08, with the labels that each got.

#2 [Setting #1] 프로젝트 초기 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/popcong/app/AppApplication.java
  src/main/java/popcong/app/infra/config/cors/CorsConfig.java
  src/main/java/popcong/app/infra/config/cors/CorsProperties.java
  src/main/java/popcong/app/infra/config/security/SecurityConfig.java
  src/main/java/popcong/app/infra/config/security/SecurityProperties.java
  src/main/resources/application.yml
  src/test/java/popcong/app/AppApplicationTests.java
  src/test/java/popcong/app/BaseTest.java
  src/test/java/popcong/app/database/DatabaseConnectionTest.java
Labels: ⚙️ Setting

#11 [Feature #10] 사용자 조회 로직 생성
  src/main/java/popcong/app/adapter/in/jwt/JwtFilter.java
  src/main/java/popcong/app/adapter/in/user/UserController.java
  src/main/java/popcong/app/adapter/out/jwt/JwtUtils.java
  src/main/java/popcong/app/adapter/out/persistence/user/repository/UserAdapter.java
  src/main/java/popcong/app/adapter/out/persistence/user/repository/UserJpaRepository.java
  src/main/java/popcong/app/application/user/dto/response/UserResponseDto.java
  src/main/java/popcong/app/application/user/port/out/LoadUserPort.java
  src/main/resources/application.yml
  src/test/java/popcong/app/auth/AuthTest.java
Labels: ✨ Feature

#18 [Feature #16] 파일 업로드 API
  .gitignore
  build.gradle
  src/main/java/popcong/app/adapter/in/user/UserController.java
  src/main/java/popcong/app/application/auth/port/in/GoogleDriveSubmitUseCase.java
  src/main/java/popcong/app/application/auth/service/GoogleDriveSubmitService.java
  src/main/java/popcong/app/application/user/port/in/UserInfoUseCase.java
  src/main/java/popcong/app/application/user/service/UserInfoService.java
  src/main/java/popcong/app/domain/user/model/DocumentType.java
  src/main/java/popcong/app/domain/user/model/SignUpUserType.java
  src/main/java/popcong/app/domain/user/model/UploadItem.java
  src/main/java/popcong/app/domain/user/model/User.java
  src/main/java/popcong/app/global/exception/error/AuthErrorCode.java
  src/main/java/popcong/app/global/exception/error/CommonErrorCode.java
  src/main/java/popcong/app/infra/config/gcp/GcpApiConfig.java
  src/main/java/popcong/app/infra/config/gcp/GcpApiProperties.java
Labels: ✨ Feature

#22 [Feature #19] 배포
  .dockerignore
  .github/workflows/release-deploy.yml
  Dockerfile
  src/main/java/popcong/app/adapter/in/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/popcong/app/global/exception/error/CommonErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feature

#24 [Fix] Github Actions workflow 수정
  .github/workflows/release-deploy.yml
Labels: 🌐 Deploy, 🔨 Fix

#26 [Deploy] 배포 2차 수정
  .github/workflows/release-deploy.yml
Labels: 🌐 Deploy, 🔨 Fix

#27 [Deploy] 1차 배포 (수정 2차)
  .github/workflows/release-deploy.yml
Labels: 🌐 Deploy

#28 [Deploy] Workflow 수정
  .github/workflows/release-deploy.yml
Labels: 🌐 Deploy, 🔨 Fix

#29 [Deploy] 1차 배포 (수정 3차)
  .github/workflows/release-deploy.yml
Labels: 🌐 Deploy

#48 [ Refactor ] 홈 화면 사용자 고유정보 수정
  src/main/java/popcong/app/adapter/out/persistence/space/repository/ReservationQueryAdapter.java
  src/main/java/popcong/app/application/user/dto/response/HomeUserResponseDto.java
  src/main/java/popcong/app/application/user/dto/response/MyReservationItemDto.java
  src/main/java/popcong/app/application/user/port/out/ReservationQueryPort.java
  src/main/java/popcong/app/application/user/port/out/WishListQueryPort.java
  src/main/java/popcong/app/application/user/service/HomeInfoService.java
Labels: ♻️ Refactor

#54 [ Fix ] : S3ProfileImageUploadAdatper 처리
  src/main/java/popcong/app/adapter/out/image/S3ProfileImageUploadAdapter.java
Labels: 🐞 Bug

#55 [Deploy] 2차 배포 수정
  src/main/java/popcong/app/adapter/out/image/S3ProfileImageUploadAdapter.java
Labels: 🌐 Deploy

#57 [ Fix ] S3 오류 확인 로그 코드 추가
  src/main/java/popcong/app/adapter/out/image/S3ProfileImageUploadAdapter.java
Labels: 🐞 Bug

#59 [Deploy] 2차 배포 수정
  src/main/java/popcong/app/adapter/in/jwt/handler/OAuth2SuccessHandler.java
Labels: 🌐 Deploy

#63 [Fix #62] user 정보 주입 방식 수정
  src/main/java/popcong/app/adapter/in/space/SpaceDetailController.java
Labels: 🐞 Bug

#74 [Deploy] 배포 수정
  src/main/java/popcong/app/infra/config/valkey/ValkeyListenerConfig.java
Labels: 🌐 Deploy

#71 [ Feature ] 예약 정보 저장하기 기능 작성
  src/main/java/popcong/app/adapter/in/space/ReservationController.java
  src/main/java/popcong/app/adapter/out/persistence/space/repository/ReservationAdapter.java
  src/main/java/popcong/app/adapter/out/persistence/space/repository/ReservationJpaRepository.java
  src/main/java/popcong/app/application/space/dto/request/SaveReservationRequestDto.java
  src/main/java/popcong/app/application/space/dto/response/SaveReservationResponseDto.java
  src/main/java/popcong/app/application/space/port/in/SaveReservationUseCase.java
  src/main/java/popcong/app/application/space/port/out/ReservationPort.java
  src/main/java/popcong/app/application/space/service/SaveReservationService.java
  src/main/java/popcong/app/global/exception/error/ReservationErrorCode.java
Labels: ✨ Feature
